image: alpine/edge
packages:
- nodejs
- npm
secrets:
- 7e6c4383-99ec-4063-bb75-04e5afad30d0

sources:
- git@git.sr.ht:~nicolaskempf57/select-a11y

tasks:
- build: |
    cd ~/select-a11y
    node --version
    npm --version
    npm ci
    npm run build
- publish: |
    cd ~/select-a11y
    echo _auth=$(< ~/NPM_TOKEN) >> .npmrc
    echo email=nicolas@conciergerie.dev >> .npmrc
    echo always-auth=true >> .npmrc
    echo scope=conciergerie-dev >> .npmrc
    npm version --no-git-tag-version $(npm view <yourProject>@latest version)
    npm version --no-git-tag-version prerelease
    npm publish